### ISSUE TITLE
Fix adaptive menue

### ISSUE THREAD

**Issue by BenLatham** [Sing-Kai/Project-WebTech#27]
Adaptive menu folds as expected, but no drop-down menu appears

**Comment by BenLatham** [comment]
The example from bootstrap uses jquery. can we do it without?

**Comment by Sing-Kai** [comment]
Tested below line
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

**Comment by Sing-Kai** [comment]
Testing
